# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnsplashImageDownload' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'UnsplashPhotoPicker', '~> 1.1'
  # Pods for UnsplashImageDownload

  target 'UnsplashImageDownloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnsplashImageDownloadUITests' do
    # Pods for testing
  end

end
